### The Salary_Train and Salary_Test datasets contains Information about Salary of different Person.
The Dataset Description as follows
- age -- age of a person
- workclass    -- A work class is a grouping of work 
- education    -- Education of an individuals    
- maritalstatus -- Marital status of an individulas    
- occupation     -- occupation of an individuals
- relationship -- ralationship of an individual    
- race --  Race of an Individual
- sex --  Gender of an Individual
- capitalgain --  profit received from the sale of an investment    
- capitalloss    -- A decrease in the value of a capital asset
- hoursperweek -- number of hours work per week    
- native -- Native of an individual
- Salary -- salary of an individual
Prepare following models to predict Salary:
1. Logistic Regression
2. Naive Bayes
3. KNN
4. SVM
5. Decision Tree
6. Random Forest
7. Adaboost

Calculate different evaluation metrics and select best model from them.

Notes:
1. Do Proper EDA.
2. Build model without dropping any columns.

Dataset:
Salary_train.csv
Salary_test.csv

### import required packages

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
from sklearn.linear_model import LogisticRegressionCV
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier

### load the data

In [23]:
df_train = pd.read_csv('./Salary_Train.csv')
df_train.head(2)

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K

In [24]:
df_test = pd.read_csv('./Salary_Test.csv')
df_test.head(2)

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K

### exploratory data analysis

In [25]:
df_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            30161 non-null  int64
 1   workclass      30161 non-null  str
 2   education      30161 non-null  str
 3   educationno    30161 non-null  int64
 4   maritalstatus  30161 non-null  str
 5   occupation     30161 non-null  str
 6   relationship   30161 non-null  str
 7   race           30161 non-null  str
 8   sex            30161 non-null  str
 9   capitalgain    30161 non-null  int64
 10  capitalloss    30161 non-null  int64
 11  hoursperweek   30161 non-null  int64
 12  native         30161 non-null  str
 13  Salary         30161 non-null  str
dtypes: int64(5), str(9)
memory usage: 5.8 MB

In [26]:
df_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            15060 non-null  int64
 1   workclass      15060 non-null  str
 2   education      15060 non-null  str
 3   educationno    15060 non-null  int64
 4   maritalstatus  15060 non-null  str
 5   occupation     15060 non-null  str
 6   relationship   15060 non-null  str
 7   race           15060 non-null  str
 8   sex            15060 non-null  str
 9   capitalgain    15060 non-null  int64
 10  capitalloss    15060 non-null  int64
 11  hoursperweek   15060 non-null  int64
 12  native         15060 non-null  str
 13  Salary         15060 non-null  str
dtypes: int64(5), str(9)
memory usage: 2.9 MB

### convert the object type into numerical type

In [27]:
from sklearn.preprocessing import LabelEncoder
def encoding(x_train, x_test):
    
    le = LabelEncoder()

    return (le.fit_transform(x_train), le.transform(x_test))

In [28]:
df_train['workclass'], df_test['workclass'] = encoding(df_train['workclass'], df_test['workclass'])
df_train['education'], df_test['education'] = encoding(df_train['education'], df_test['education'])
df_train['maritalstatus'], df_test['maritalstatus'] = encoding(df_train['maritalstatus'], df_test['maritalstatus'])
df_train['occupation'], df_test['occupation'] = encoding(df_train['occupation'], df_test['occupation'])
df_train['relationship'], df_test['relationship'] = encoding(df_train['relationship'], df_test['relationship'])
df_train['race'], df_test['race'] = encoding(df_train['race'], df_test['race'])
df_train['sex'], df_test['sex'] = encoding(df_train['sex'], df_test['sex'])
df_train['native'], df_test['native'] = encoding(df_train['native'], df_test['native'])
df_train['Salary'], df_test['Salary'] = encoding(df_train['Salary'], df_test['Salary'])

In [29]:
df_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            30161 non-null  int64
 1   workclass      30161 non-null  int64
 2   education      30161 non-null  int64
 3   educationno    30161 non-null  int64
 4   maritalstatus  30161 non-null  int64
 5   occupation     30161 non-null  int64
 6   relationship   30161 non-null  int64
 7   race           30161 non-null  int64
 8   sex            30161 non-null  int64
 9   capitalgain    30161 non-null  int64
 10  capitalloss    30161 non-null  int64
 11  hoursperweek   30161 non-null  int64
 12  native         30161 non-null  int64
 13  Salary         30161 non-null  int64
dtypes: int64(14)
memory usage: 3.2 MB

In [30]:
df_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            15060 non-null  int64
 1   workclass      15060 non-null  int64
 2   education      15060 non-null  int64
 3   educationno    15060 non-null  int64
 4   maritalstatus  15060 non-null  int64
 5   occupation     15060 non-null  int64
 6   relationship   15060 non-null  int64
 7   race           15060 non-null  int64
 8   sex            15060 non-null  int64
 9   capitalgain    15060 non-null  int64
 10  capitalloss    15060 non-null  int64
 11  hoursperweek   15060 non-null  int64
 12  native         15060 non-null  int64
 13  Salary         15060 non-null  int64
dtypes: int64(14)
memory usage: 1.6 MB

In [31]:
df_train.corr()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
age,1.000000,0.080537,-0.001091,0.043525,-0.276363,-0.005682,-0.246452,0.023380,0.081972,0.080152,0.060278,0.101598,-0.001548,0.241991
workclass,0.080537,1.000000,0.017864,0.037833,-0.034235,0.015572,-0.067414,0.044734,0.074966,0.035349,0.007244,0.050723,0.007598,0.018040
education,-0.001091,0.017864,1.000000,0.345420,-0.040704,-0.038213,-0.012732,0.011139,-0.027831,0.030582,0.014822,0.059892,0.079715,0.079013
educationno,0.043525,0.037833,0.345420,1.000000,-0.063419,0.087717,-0.091935,0.032805,0.006155,0.124416,0.079691,0.152522,0.092625,0.335287
maritalstatus,-0.276363,-0.034235,-0.040704,-0.063419,1.000000,0.022655,0.177955,-0.068641,-0.119774,-0.042414,-0.035385,-0.189004,-0.026057,-0.193504
occupation,-0.005682,0.015572,-0.038213,0.087717,0.022655,1.000000,-0.053727,0.000717,0.062316,0.022162,0.014612,0.018365,-0.003298,0.051577
relationship,-0.246452,-0.067414,-0.012732,-0.091935,0.177955,-0.053727,1.000000,-0.117148,-0.584881,-0.058257,-0.063659,-0.257850,-0.010661,-0.250998
race,0.023380,0.044734,0.011139,0.032805,-0.068641,0.000717,-0.117148,1.000000,0.089207,0.014355,0.023461,0.048533,0.126507,0.071666
sex,0.081972,0.074966,-0.027831,0.006155,-0.119774,0.062316,-0.584881,0.089207,1.000000,0.048809,0.047285,0.231272,0.000063,0.216680
capitalgain,0.080152,0.035349,0.030582,0.124416,-0.042414,0.022162,-0.058257,0.014355,0.048809,1.000000,-0.032218,0.080431,0.008513,0.221195
capitalloss,0.060278,0.007244,0.014822,0.079691,-0.035385,0.014612,-0.063659,0.023461,0.047285,-0.032218,1.000000,0.052454,0.010193,0.150222
hoursperweek,0.101598,0.050723,0.059892,0.152522,-0.189004,0.018365,-0.257850,0.048533,0.231272,0.080431,0.052454,1.000000,0.008429,0.229480
native,-0.001548,0.007598,0.079715,0.092625,-0.026057,-0.003298,-0.010661,0.126507,0.000063,0.008513,0.010193,0.008429,1.000000,0.023515
Salary,0.241991,0.018040,0.079013,0.335287,-0.193504,0.051577,-0.250998,0.071666,0.216680,0.221195,0.150222,0.229480,0.023515,1.000000

In [32]:
df_test.corr()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
age,1.000000,0.096037,-0.007948,0.026123,-0.262577,-0.002214,-0.249701,0.024485,0.082265,0.078760,0.057745,0.102758,-0.005683,0.227469
workclass,0.096037,1.000000,0.018005,0.046623,-0.031329,0.021271,-0.060235,0.059749,0.059161,0.032980,0.010242,0.052614,-0.003635,0.011008
education,-0.007948,0.018005,1.000000,0.351486,-0.043117,-0.023999,-0.014227,0.012133,-0.026978,0.028626,0.020568,0.062892,0.077065,0.085554
educationno,0.026123,0.046623,0.351486,1.000000,-0.068079,0.093643,-0.081413,0.029355,-0.002052,0.131750,0.085817,0.133691,0.097188,0.327813
maritalstatus,-0.262577,-0.031329,-0.043117,-0.068079,1.000000,0.003854,0.185495,-0.073718,-0.120374,-0.042405,-0.034073,-0.171665,-0.016532,-0.191058
occupation,-0.002214,0.021271,-0.023999,0.093643,0.003854,1.000000,-0.047381,-0.001561,0.045244,0.014165,0.016580,0.011755,-0.001311,0.046218
relationship,-0.249701,-0.060235,-0.014227,-0.081413,0.185495,-0.047381,1.000000,-0.121481,-0.579212,-0.054040,-0.048091,-0.261905,0.000500,-0.258335
race,0.024485,0.059749,0.012133,0.029355,-0.073718,-0.001561,-0.121481,1.000000,0.088450,0.013539,0.015799,0.037125,0.125514,0.069227
sex,0.082265,0.059161,-0.026978,-0.002052,-0.120374,0.045244,-0.579212,0.088450,1.000000,0.044843,0.045360,0.231744,-0.014178,0.213863
capitalgain,0.078760,0.032980,0.028626,0.131750,-0.042405,0.014165,-0.054040,0.013539,0.044843,1.000000,-0.031876,0.090501,0.005923,0.220882
capitalloss,0.057745,0.010242,0.020568,0.085817,-0.034073,0.016580,-0.048091,0.015799,0.045360,-0.031876,1.000000,0.057712,-0.001008,0.145967
hoursperweek,0.102758,0.052614,0.062892,0.133691,-0.171665,0.011755,-0.261905,0.037125,0.231744,0.090501,0.057712,1.000000,0.005877,0.222665
native,-0.005683,-0.003635,0.077065,0.097188,-0.016532,-0.001311,0.000500,0.125514,-0.014178,0.005923,-0.001008,0.005877,1.000000,0.014056
Salary,0.227469,0.011008,0.085554,0.327813,-0.191058,0.046218,-0.258335,0.069227,0.213863,0.220882,0.145967,0.222665,0.014056,1.000000

In [33]:
df_train['Salary'].value_counts()

Salary
0    22653
1     7508
Name: count, dtype: int64

In [34]:
df_test['Salary'].value_counts()

Salary
0    11360
1     3700
Name: count, dtype: int64

In [35]:
df_train.describe()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
count,30161.000000,30161.00000,30161.00000,30161.000000,30161.000000,30161.000000,30161.000000,30161.000000,30161.000000,30161.000000,30161.000000,30161.000000,30161.000000,30161.000000
mean,38.438115,2.19933,10.33361,10.121316,2.580087,5.959849,1.418322,3.678592,0.675707,1092.044064,88.302311,40.931269,35.413481,0.248931
std,13.134830,0.95394,3.81226,2.550037,1.498018,4.029633,1.601361,0.834721,0.468118,7406.466611,404.121321,11.980182,5.956430,0.432401
min,17.000000,0.00000,0.00000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,28.000000,2.00000,9.00000,9.000000,2.000000,2.000000,0.000000,4.000000,0.000000,0.000000,0.000000,40.000000,37.000000,0.000000
50%,37.000000,2.00000,11.00000,10.000000,2.000000,6.000000,1.000000,4.000000,1.000000,0.000000,0.000000,40.000000,37.000000,0.000000
75%,47.000000,2.00000,12.00000,13.000000,4.000000,9.000000,3.000000,4.000000,1.000000,0.000000,0.000000,45.000000,37.000000,0.000000
max,90.000000,6.00000,15.00000,16.000000,6.000000,13.000000,5.000000,4.000000,1.000000,99999.000000,4356.000000,99.000000,39.000000,1.000000

In [36]:
df_test.describe()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
count,15060.000000,15060.000000,15060.000000,15060.000000,15060.000000,15060.000000,15060.000000,15060.000000,15060.000000,15060.000000,15060.000000,15060.000000,15060.000000,15060.000000
mean,38.768327,2.214874,10.272377,10.112749,2.595286,5.989044,1.401394,3.683665,0.673772,1120.301594,89.041899,40.951594,35.467596,0.245684
std,13.380676,0.966422,3.826251,2.558727,1.505336,4.020113,1.588954,0.827630,0.468848,7703.181842,406.283245,12.062831,5.880922,0.430506
min,17.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,28.000000,2.000000,9.000000,9.000000,2.000000,2.000000,0.000000,4.000000,0.000000,0.000000,0.000000,40.000000,37.000000,0.000000
50%,37.000000,2.000000,11.000000,10.000000,2.000000,6.000000,1.000000,4.000000,1.000000,0.000000,0.000000,40.000000,37.000000,0.000000
75%,48.000000,2.000000,12.000000,13.000000,4.000000,9.000000,3.000000,4.000000,1.000000,0.000000,0.000000,45.000000,37.000000,0.000000
max,90.000000,6.000000,15.000000,16.000000,6.000000,13.000000,5.000000,4.000000,1.000000,99999.000000,3770.000000,99.000000,39.000000,1.000000

In [37]:
x_train = df_train.drop('Salary', axis = 1)
y_train = df_train['Salary']

In [38]:
x_test = df_test.drop('Salary', axis = 1)
y_test = df_test['Salary']

### train the model

In [39]:
def logistic_model():

    model = LogisticRegressionCV()
    model.fit(x_train, y_train)
    return model

In [40]:
def naive_bayes():

    model = GaussianNB()
    model.fit(x_train, y_train)

    return model

In [41]:
def knn():

    model = KNeighborsClassifier(n_neighbors=5)
    model.fit(x_train, y_train)

    return model

In [42]:
def svm():

    model = SVC()
    model.fit(x_train, y_train)

    return model

In [56]:
def decision_tree():

    model = DecisionTreeClassifier(max_depth=5)
    model.fit(x_train, y_train)

    return model

In [57]:
def random_forest():

    model = RandomForestClassifier(n_estimators=100, max_depth=5)
    model.fit(x_train, y_train)

    return model

In [58]:
def adaboost():

    model = AdaBoostClassifier()
    model.fit(x_train, y_train)

    return model

In [59]:
models = [
    {"name": "Logistics Regression", "model": logistic_model()},
    {"name": "Naive Bayes", "model": naive_bayes()},
    {"name": "KNN", "model": knn()},
    {"name": "SVM", "model": svm()},
    {"name": "Decision Tree", "model": decision_tree()},
    {"name": "Random Forest", "model": random_forest()},
    {"name": "AdaBoost", "model": adaboost()},
]

C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1780: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1823: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of LogisticRegressionCV for more details.
  warnings.warn(
C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

### evaluate the model

In [60]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def evaluate(model, name, x, y):
    y_pred = model.predict(x)

    accuracy = accuracy_score(y,y_pred)
    precision = precision_score(y,y_pred)
    recall = recall_score(y,y_pred)
    f1 = f1_score(y,y_pred)

    return name , accuracy, precision, recall, f1

In [61]:
metrics_train = []

for model_info in models:

    metrics_train.append(evaluate(model_info['model'], model_info['name'], x_train, y_train))

metrics_train_df = pd.DataFrame(metrics_train, columns=['Algorithm', 'Accuracy', 'Precision', 'Recall', 'F1 Score'])
metrics_train_df

              Algorithm  Accuracy  Precision    Recall  F1 Score
0  Logistics Regression  0.811445   0.707829  0.413026  0.521659
1           Naive Bayes  0.795332   0.683834  0.330714  0.445821
2                   KNN  0.883691   0.790782  0.724427  0.756152
3                   SVM  0.796028   0.745474  0.274241  0.400974
4         Decision Tree  0.844335   0.783855  0.517315  0.623285
5         Random Forest  0.846689   0.806287  0.505594  0.621480
6              AdaBoost  0.846557   0.784810  0.528503  0.631646

In [62]:
metrics_test = []

for model_info in models:

    metrics_test.append(evaluate(model_info['model'], model_info['name'], x_test, y_test))

metrics_test_df = pd.DataFrame(metrics_test,  columns=['Algorithm', 'Accuracy', 'Precision', 'Recall', 'F1 Score'])
metrics_test_df

              Algorithm  Accuracy  Precision    Recall  F1 Score
0  Logistics Regression  0.811554   0.697344  0.411622  0.517675
1           Naive Bayes  0.794688   0.667956  0.326757  0.438838
2                   KNN  0.835525   0.677298  0.631351  0.653518
3                   SVM  0.796414   0.733088  0.269459  0.394071
4         Decision Tree  0.841766   0.769105  0.508649  0.612331
5         Random Forest  0.844024   0.794079  0.492973  0.608304
6              AdaBoost  0.846414   0.777289  0.525405  0.626996